import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "News Feed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
            <SignedIn>
              <div className="absolute top-20 left-4 z-50">
                <UserButton />
              </div>
              <main>{children}</main>
            </SignedIn>
          </header>
        </body>
      </html>
    </ClerkProvider>
  );
}
